tests for 7-base_geometry.py
-------------------------------------

    >>> BaseGeometry = __import__('7-base_geometry').BaseGeometry

case 1: Passing an integer

    >>> bg = BaseGeometry()
    >>> bg.integer_validator("name", 5)

-------------------------------------------

case 2: Passing a string

    >>> bg = BaseGeometry()
    >>> bg.integer_validator("name", "John")
    Traceback (most recent call last):
        ...
    TypeError: name must be an integer

---------------------------------------------

case 3: Passing a negative integer

    >>> bg = BaseGeometry()
    >>> bg.integer_validator("my_int", -12)
    Traceback (most recent call last):
        ...
    ValueError: my_int must be greater than 0

---------------------------------------------

case 4: Passing a float

    >>> bg = BaseGeometry()
    >>> bg.integer_validator("name", "12.3")
    Traceback (most recent call last):
        ...
    TypeError: name must be an integer


    >>> bg = BaseGeometry()
    >>> bg.integer_validator("name", "12.0")
    Traceback (most recent call last):
        ...
    TypeError: name must be an integer

---------------------------------------------

case 5: Passing no arguement

    >>> bg = BaseGeometry()
    >>> bg.integer_validator()
    Traceback (most recent call last):
        ...
    TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

----------------------------------------------

case 6: Passing one arguement

    >>> bg = BaseGeometry()
    >>> bg.integer_validator("name")
    Traceback (most recent call last):
        ...
    TypeError: integer_validator() missing 1 required positional argument: 'value'


    >>> bg = BaseGeometry()
    >>> bg.integer_validator(5)
    Traceback (most recent call last):
        ...
    TypeError: integer_validator() missing 1 required positional argument: 'value'

----------------------------------------------

case 7: Passing zero

    >>> bg = BaseGeometry()
    >>> bg.integer_validator("name", 0)
    Traceback (most recent call last):
        ...
    ValueError: name must be greater than 0
